/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./src/**/*.{js,jsx,ts,tsx,html}",
        "./pages/**/*.{js,ts,jsx,tsx}",
        "./app/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                background: "var(--color-background)",
                foreground: "var(--color-foreground)",
                primary: "var(--color-primary)",
                primaryHover: "var(--color-primary-hover)",
                primaryActive: "var(--color-primary-active)",
                primaryDisabled: "var(--color-primary-disabled)",
                secondary: "var(--color-secondary)",
                secondaryHover: "var(--color-secondary-hover)",
                secondaryActive: "var(--color-secondary-active)",
                success: "var(--color-success)",
                warning: "var(--color-warning)",
                error: "var(--color-error)",
                info: "var(--color-info)",
                muted: "var(--color-muted)",
                border: "var(--color-border)",
            },
            fontFamily: {
                sans: ["var(--font-sans)"],
                mono: ["var(--font-mono)"],
                display: ["var(--font-display)"],
            },
            fontSize: {
                xs: ["var(--font-size-xs)", { lineHeight: "var(--line-height-tight)" }],
                sm: ["var(--font-size-sm)", { lineHeight: "var(--line-height-tight)" }],
                base: ["var(--font-size-base)", { lineHeight: "var(--line-height-normal)" }],
                lg: ["var(--font-size-lg)", { lineHeight: "var(--line-height-snug)" }],
                xl: ["var(--font-size-xl)", { lineHeight: "var(--line-height-normal)" }],
                "2xl": ["var(--font-size-2xl)", { lineHeight: "var(--line-height-tight)" }],
                "3xl": ["var(--font-size-3xl)", { lineHeight: "var(--line-height-tight)" }],
                "4xl": ["var(--font-size-4xl)", { lineHeight: "var(--line-height-tight)" }],
                "5xl": ["var(--font-size-5xl)", { lineHeight: "var(--line-height-relaxed)" }],
            },
            lineHeight: {
                none: "var(--line-height-none)",
                tight: "var(--line-height-tight)",
                snug: "var(--line-height-snug)",
                normal: "var(--line-height-normal)",
                relaxed: "var(--line-height-relaxed)",
            },
            spacing: {
                "1": "var(--space-1)",
                "2": "var(--space-2)",
                "3": "var(--space-3)",
                "4": "var(--space-4)",
                "5": "var(--space-5)",
                "6": "var(--space-6)",
                "8": "var(--space-8)",
                "10": "var(--space-10)",
                "12": "var(--space-12)",
                "16": "var(--space-16)",
            },
            borderRadius: {
                DEFAULT: "var(--color-radius)",
            },
            boxShadow: {
                DEFAULT: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
                sm: "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.05)",
                md: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
                lg: "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
            },
        },
    },
    plugins: [],
}